# Generated by Django 6.0.1 on 2026-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_cart_session_key_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'fruits'), ('vegitable', 'vegitable')], default='fruits'),
        ),
    ]
