# Generated by Django 6.0.1 on 2026-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_category_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'fruits'), ('vegitable', 'vegitable')], default='fruits', max_length=20),
        ),
    ]
